# TensorFlow Basics

In [2]:
import tensorflow as tf

In [3]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [9]:
const = tf.constant(10)

In [10]:
fill_mat = tf.fill((4,4),10)

In [11]:
myzeros = tf.zeros((4,4))

In [12]:
myones = tf.ones((4,4))

In [13]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [14]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [15]:
with tf.Session() as sess:
    result = sess.run(myrandn)
result

array([[ 0.09356131,  1.57866549,  0.60653782,  0.06490874],
       [ 0.26212353,  0.95169193, -0.71365124, -0.68807471],
       [ 0.53718424, -0.17379099, -0.32569802,  0.21763581],
       [ 1.00190008, -0.35656762, -0.24892075, -0.00284772]], dtype=float32)

In [16]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [18]:
sess = tf.InteractiveSession()

for op in my_ops:
    print(sess.run(op))
    print(op.eval())

10
10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.13790753 -0.43431506 -0.28563613  0.45373288]
 [ 0.21545041  0.0991345   0.00768181 -0.57906801]
 [ 0.08459502  0.06012735 -0.92096525  0.68434489]
 [ 0.25572649  0.19862643 -0.40135589  0.82107908]]
[[-0.11535507  0.88220203  1.07049072  0.56907135]
 [ 0.21012069  0.38764071  0.3048549   0.83666497]
 [ 0.38332391  0.7006405  -0.3087365  -0.4185181 ]
 [ 0.59675878 -0.1574735   0.91086173 -0.06392761]]
[[ 0.42682981  0.75865126  0.72309637  0.20944309]
 [ 0.69729221  0.41979039  0.44798982  0.96363378]
 [ 0.07000422  0.13278055  0.32637298  0.1208725 ]
 

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.1066899  -0.67079175 -0.17030844 -0.94966197]
 [ 0.36453074  0.07695128  0.75996757  0.26596269]
 [ 0.09675932  0.0172567   0.61638004 -0.55172282]
 [ 0.02814705 -0.61808312 -0.35328296  0.08349258]]


[[ 0.68672144  0.84300661  0.01917613  0.15367568]
 [ 0.8822968   0.6406256   0.11968935  0.34425914]
 [ 0.32183003  0.31339324  0.0376581   0.34806168]
 [ 0.00820863  0.74296677  0.67269909  0.48290253]]




## Matrix Multiplication

In [27]:
a = tf.constant([ [1,2],
                  [3,4],
                [3,4]])

In [28]:
a.get_shape()

TensorShape([Dimension(3), Dimension(2)])

In [29]:
b = tf.constant([[10],[100]])

In [30]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [31]:
result = tf.matmul(a,b)

In [32]:
result.eval()

array([[210],
       [430],
       [430]])

In [33]:
result.get_shape()


TensorShape([Dimension(3), Dimension(1)])